{
 "title": "Liberty-Metrics",
 "description": "Dashboard for OpenLiberty  v19.0.0.12",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "servlet", "label": "Servlet", "query": "vendor_servlet_request_total" },
   { "name": "dur", "label": "Moving Average", "query": "15s" },
   {
    "name": "connection_pools",
    "query": "vendor_connectionpool_usedConnections_total"
   },
   {
    "name": "thread_pools",
    "query": "vendor_threadpool_activeThreads"
   }
  ]
 },
 "panels": [
  { "title": "Servlet (${servlet})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "servlet" },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(vendor_servlet_request_total[$dur])",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vendor_servlet_responseTime_total_seconds[$dur])/rate(vendor_servlet_request_total[$dur])",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Connection Pool (${connection_pools})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "connection_pools",
   "collapsed": true,
   "panels": [
    {
     "title": "Used connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_usedConnections_total[$dur])",
       "legendFormat": "Used connections"
      }
     ]
    },
    {
     "title": "In Use Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_inUseTime_total_seconds[$dur])/rate(vendor_connectionpool_usedConnections_total[$dur])",
       "legendFormat": "In use time"
      }
     ]
    },
    {
     "title": "Wait Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_waitTime_total_seconds[$dur])/rate(vendor_connectionpool_usedConnections_total[$dur])",
       "legendFormat": "Wait time"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_managedConnections",
       "legendFormat": "Managed"
      },
      {
       "expr": "vendor_connectionpool_connectionHandles",
       "legendFormat": "Used"
      },
      {
       "expr": "vendor_connectionpool_freeConnections",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Created / destroyed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(vendor_connectionpool_create_total[$dur])",
       "legendFormat": "Created"
      },
      {
       "expr": "increase(vendor_connectionpool_destroy_total[$dur])",
       "legendFormat": "Destroyed"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool (${thread_pools})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "thread_pools",
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_activeThreads",
       "legendFormat": "Active"
      },
      { "expr": "vendor_threadpool_size", "legendFormat": "Pool size" }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "vendor_session_activeSessions", "legendFormat": "Active" },
      { "expr": "vendor_session_liveSessions", "legendFormat": "Live" }
     ]
    },
    {
     "title": "Created / Invalidated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(vendor_session_create_total[$dur])",
       "legendFormat": "Created"
      },
      {
       "expr": "increase(vendor_session_invalidatedbyTimeout_total[$dur])",
       "legendFormat": "Invalidated"
      }
     ]
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load Percent",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "base_cpu_processCpuLoad_percent",
       "legendFormat": "CPU load"
      }
     ]
    },
    {
     "title": "CPU System Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "base_cpu_systemLoadAverage", "legendFormat": "System load average" }
     ]
    },
    {
     "title": "Available CPU Processors",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "base_cpu_availableProcessors" }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(base_memory_usedHeap_bytes/base_memory_maxHeap_bytes)",
       "legendFormat": "Heap usage"
      }
     ]
    },
    {
     "title": "Used Heap",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 27 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      { "expr": "base_memory_usedHeap_bytes" }
     ]
    },
    {
     "title": "Max Heap Size",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 27 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      { "expr": "base_memory_maxHeap_bytes" }
     ]
    },
    {
     "title": "JVM Uptime",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
     "format": "s",
     "valueName": "current",
     "targets": [
      { "expr": "base_jvm_uptime_seconds" }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "base_thread_count", "legendFormat": "Threads" },
      { "expr": "base_thread_daemon_count", "legendFormat": "Daemon threads" }
     ]
    },
    {
     "title": "Loaded / Unloaded Classes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(base_classloader_loadedClasses_count[$dur])",
       "legendFormat": "Loaded"
      },
      {
       "expr": "rate(base_classloader_unloadedClasses_total[$dur])",
       "legendFormat": "Unloaded"
      }
     ]
    },
    {
     "title": "Loaded Classes",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 43 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "base_classloader_loadedClasses_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time per Scavenge GC Cycle",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds[$dur]) / rate(base_gc_total[$dur])",
       "legendFormat": "Time per scavenge GC"
      }
     ]
    },
    {
     "title": "Time per Global GC Cycle",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds[$dur]) / rate(base_gc_total[$dur])",
       "legendFormat": "Time per global GC"
      }
     ]
    }
   ]
  }
 ]
}